git:
  depth: false
  submodules: false
language: node_js
addons:
  chrome: stable
cache: yarn
env:
  - PUBLIC_ASSETS=assets
  - CC_TEST_REPORTER_ID=a0d2ee3be59b9405db751a49ed37d5fd685b69ea5bee294c5ed802058a4df745

install:
  - yarn install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - yarn unit

before_deploy:
  - yarn run build --report
  - tar -zcf ${PUBLIC_ASSETS}.tar.gz public
  - git tag "${TRAVIS_BRANCH}/$(date +'%Y-%m/%d_%H%M%S')/$(git log --format=%h -1)"

deploy:
  provider: releases
  api_key:
    secure: te8u+yNtVxFlzsVvllaLbk/BnY8ljI8AVF/BTWvW4p+d9SK3dSpuWR3Uv8MhpHDum7tHxyXezdyWpWw9WVmn1Gp8fUf6eKzglnpkArG2Kn6wSH27flhm7PqcS2JLCWC4YPytj5Fbn1PejlP2ktQ4WPrwRVeeaMZh4Od56zmPepDMi2ABZqvEMl9oLckCRdnrwYKDg6dvbpqPUvPwkrvY/9fpz2kiyd0Ne89MVhfALU+K/H4V4rtVq8FNjVbaR7fMkyCjdUeLMWeEViY0ni08S9yMpkEz5qiUJmPFVosP3H0gOG0bjkooJmpk68ygUgaWrSPm2tPtFizJBHY7iR3Xi06lzq7KaO8qWaUfsX85OnvpjgTNa41bXG+4nznd5KwD/e0kU5o6vRKGaAv5Z3/0WagIT8S0VHzRIKsP6sgkgac1qoTaFFjCKbHTczKtNTqA7QOAiceYZM7H6sm23XsJP2RRShmZam8o1rjHzHWkNHlHm7YvZf1IvCDjHIOBjgXBMe7QTXRfD+wgcpQbmZhM+C3BxtrbAZjdxVQmq2E4W+7yg/Ff9v4/HXdR7egNmxDxe+tlVtTfRegjO6KWx/J5QmLqXzARQdMQ0FuFQkrawFY4qXoRF1R7+rs8b9B3GhewLCjztWeyP5HWW/hspxGqaVIc8v23bSHNrhAxlnPhB4Q=
  file_glob: true
  file: ${PUBLIC_ASSETS}.tar.gz
  skip_cleanup: true
  on:
    repo: sanger/sequencescape-aker-inbox
    branch: fix-deployment

after_script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
